---
- include_vars: roles/ec2_keys/vars/main.yml
- name: lunching ec2
  ec2:
    key_name: "{{ key }}"
    instance_type: t2.micro
    image: ami-d732f0b7
    group: docker
    region: us-west-2
    

 
